### ISSUE TITLE
Support for work profile apps.

### ISSUE THREAD

**Issue by OulipianSummer** [peterfajdiga/FastDraw#33] opened 2024-06-23 20:56 UTC
Issue: My phone uses a work profile (using Island, though other solutions are available) to sandbox apps that don't respect privacy. Fast Draw does not locate these apps or show icons for them in the interface, so they are not able to be used at all in this launcher.

Proposed Solution: Display apps in the work profile with a badge so I can identify the fact that they are installed on that profile. Suggestion for the badge is a briefcase logo, which is standard for most launchers.

**Comment by peterfajdiga** [comment] 2024-06-30 20:56
Duplicate of https://github.com/peterfajdiga/FastDraw/issues/8.

**Closed by peterfajdiga** 2024-06-30 20:56 UTC
