### ISSUE TITLE
Icon pack support 

### ISSUE THREAD

**Issue by Donnnno** [peterfajdiga/FastDraw#28] opened 2024-02-26 09:56 UTC
It would be great if FastDraw supported icon packs, like most launchers do. It gives the users more freedom to customize their homescreen :)

**Comment by peterfajdiga** [comment] 2024-03-10 21:01
Duplicate of #13.

I agree it would be great, but I don't have the time to implement and maintain most of the other launcher's features. :(

Seeing that this is a popular request, I'll leave the issue open.

**Comment by peterfajdiga** [comment] 2024-03-10 21:03
Duplicate of #13.

I agree it would be great, but I don't have the time to implement and maintain most of the other launcher's features. :(

Seeing that this is a popular request, I'll re-open the original issue.

**Closed by peterfajdiga** 2024-03-10 21:03 UTC

**Comment by Donnnno** [comment] 2024-03-10 21:14
Totally understandable, I understand the struggle of not having enough time to maintain a project.
